### ISSUE TITLE
Add 'Language' as a new property

### ISSUE THREAD

**Issue by kathrinblagec** [OpenBioLink/ITO#13]
Perhaps not a priority but still interesting since NLP resources are so heavily focused on a small set of languages (e.g., English, Chinese) with a lack of resources and datasets for many other languages. 

Use cases:
- There are initiatives to increase resources for low-resource languages to make NLP technologies more widely accessible, e.g., in African countries. [1-3] Including language information in the ontology could help to show which resources are available and which are lacking, and might also be interesting for answering questions on cross-lingual transfer (e.g., does an approach work better on certain language clusters and which ones?)
- Some NLP-specific metrics do not measure performance equally well across different languages.

Languages could be grouped by existing taxonomies of language families (e.g., https://www.freelang.net/families/families_summary.php)

[1] https://www.masakhane.io/
[2] https://arxiv.org/abs/1906.05685
[3] http://www.marekrei.com/blog/geographic-diversity-of-nlp-conferences/

**Comment by matthias-samwald** [comment]
Added languages under the loosely formalized 'Topic' branch now. Will only add languages that are represented in the datasets we deal with (e.g. English, Spanish, Chinese etc.)
